from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from .parser import ApiSpec

TEMPLATE_DIR = Path(__file__).parent / "templates"

_env = Environment(
    loader=FileSystemLoader(str(TEMPLATE_DIR)),
    autoescape=select_autoescape(disabled_extensions=("j2",)),
    trim_blocks=True,
    lstrip_blocks=True,
)


def render_server(spec: ApiSpec) -> str:
    template = _env.get_template("server.py.j2")
    return template.render(spec=spec)


def write_server(spec: ApiSpec, out_dir: str) -> Path:
    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    code = render_server(spec)
    server_file = out_path / "server.py"
    server_file.write_text(code)

    readme = out_path / "README.md"
    tool_lines = "\n".join(f"- `{op.func_name}` — {op.summary or (op.method.upper() + ' ' + op.path)}" for op in spec.operations)
    readme.write_text(
        f"""# {spec.title} — MCP Server

Generated by [api2mcp](https://github.com/plagueson/api2mcp) from an OpenAPI spec.

## Setup

```bash
pip install "mcp[cli]" requests
export API_BASE_URL="{spec.base_url}"
export API_KEY="your-key-if-needed"
python server.py
```

## Tools ({len(spec.operations)})

{tool_lines}
"""
    )
    return server_file
